/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATypographyLink: typeof import('ant-design-vue/es')['TypographyLink']
    Company: typeof import('./src/components/Company.vue')['default']
    CompanyForm: typeof import('./src/components/company/CompanyForm.vue')['default']
    CompanyList: typeof import('./src/components/company/CompanyList.vue')['default']
    Content: typeof import('./src/components/Content.vue')['default']
    Depart: typeof import('./src/components/Depart.vue')['default']
    DepartList: typeof import('./src/components/DepartList.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MenuDrawer: typeof import('./src/components/MenuDrawer.vue')['default']
    MenuList: typeof import('./src/components/MenuList.vue')['default']
    MenuSonDrawer: typeof import('./src/components/MenuSonDrawer.vue')['default']
    MutiSelect: typeof import('./src/components/MutiSelect.vue')['default']
    PositionForm: typeof import('./src/components/position/PositionForm.vue')['default']
    PositionList: typeof import('./src/components/position/PositionList.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RoleList: typeof import('./src/components/RoleList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/Test.vue')['default']
    UserList: typeof import('./src/components/UserList.vue')['default']
    UserManagement: typeof import('./src/components/UserManagement.vue')['default']
  }
}
